var sample = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "!",
  "@",
  "#",
  r"$",
  "%",
  "^",
  "&",
  "*",
  r"$",
  "?",
];
var defLt = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

Map data = {
  0: {
    "a": "87yhj8ik",
    "b": "4eserds",
    "c": "54er",
    "d": "iuhj9ij",
    "e": "ui87yhj",
    "f": "87ygftyu",
    "g": "oijkokmn",
    "h": "9ijiok",
    "i": "6yh",
    "j": "7ujh",
    "k": "4rfr5rg",
    "l": "7uji",
    "m": "i9o0p",
    "n": "ujjuik",
    "o": "09io0",
    "p": "okmoplk",
    "q": "76yu7uj",
    "r": "y7ujju78",
    "s": "98ikj",
    "t": "uio8ikl",
    "u": "7ui88io",
    "v": "8iko0",
    "w": "4r5t6",
    "x": "8i9u",
    "y": "t6y7yg",
    "z": "78uhj",
    "A": r"$ES$RFER",
    "B": "%TG%^YTTYHG",
    "C": "&^TGH",
    "D": "UHBUIKMNB",
    "E": "YHNMYUHJ",
    "F": "YGVYUGH",
    "G": "*&YHJIK",
    "H": "UHBIJNHJ",
    "I": "&*(*UHGHJ",
    "J": "*IKJ",
    "K": "YHNHUHM",
    "L": "YGVB",
    "M": "CFTGBHUJM",
    "N": "YGVYHNJI",
    "O": "(*UI(",
    "P": "YHNYUJH",
    "Q": "&^TGHU&J",
    "R": "^YH^&UYJ",
    "S": "(*&UJMNB",
    "T": "%^&^YH",
    "U": "%TGHJU&",
    "V": "YHNJI",
    "W": "TGBHUJMKO",
    "X": "&UJ*UH",
    "Y": "&U(IJN",
    "Z": "WERRDXXCV"
  },
  1: {
    "a": "76tgh7uj",
    "b": "3wawesa",
    "c": "43we",
    "d": "uygh8uh",
    "e": "yu76tgh",
    "f": "76tfdrty",
    "g": "iuhjijnb",
    "h": "8uhuij",
    "i": "5tg",
    "j": "6yhg",
    "k": "3ede4ef",
    "l": "6yhu",
    "m": "u8i9o",
    "n": "yhhyuj",
    "o": "98ui9",
    "p": "ijniokj",
    "q": "65ty6yh",
    "r": "t6yhhy67",
    "s": "87ujh",
    "t": "yui7ujk",
    "u": "6yu77ui",
    "v": "7uji9",
    "w": "3e4r5",
    "x": "7i8y",
    "y": "r5t6tf",
    "z": "67ygh",
    "A": "#WA#EDWE",
    "B": r"$RF$%TRRTGF",
    "C": "^%RFG",
    "D": "YGVYUJNBV",
    "E": "TGBNTYGH",
    "F": "TFCTYFG",
    "G": "&^TGHUJ",
    "H": "YGVUHBGH",
    "I": "^&*&YGFGH",
    "J": "&UJH",
    "K": "TGBGYGN",
    "L": "TFCV",
    "M": "XDRFVGYHN",
    "N": "TFCTGBHU",
    "O": "*&YU*",
    "P": "TGBTYHG",
    "Q": "^%RFGY^H",
    "R": "%TG%^YTH",
    "S": "*&^YHNBV",
    "T": r"$%^%TG",
    "U": r"$RFGHY^",
    "V": "TGBHU",
    "W": "RFVGYHNJI",
    "X": "^YH&YG",
    "Y": "^Y*UHB",
    "Z": "QWEESZZXC"
  },
  2: {
    "a": "98ujk9ol",
    "b": "5rdrtf",
    "c": "65rt",
    "d": "oijk0ok",
    "e": "io98ujk",
    "f": "98uhgyui",
    "g": "poklpl,m",
    "h": "0okopl",
    "i": "7uj",
    "j": "8ikj",
    "k": "5tgt6th",
    "l": "8iko",
    "m": "o0p-[",
    "n": "ikkiol",
    "o": "-0op-",
    "p": "pl,p[;l",
    "q": "87ui8ik",
    "r": "u8ikki89",
    "s": "09olk",
    "t": "iop9ol;",
    "u": "8io99op",
    "v": "9olp-",
    "w": "5t6y7",
    "x": "9o0i",
    "y": "y7u8uh",
    "z": "89ijk",
    "A": "%RD%TGRT",
    "B": "^YH^&UYYUJH",
    "C": "*&YHJ",
    "D": "IJNIOL<MN",
    "E": "UJM<UIJK",
    "F": "UHBUIHJ",
    "G": "(*UJKOL",
    "H": "IJNOKMJK",
    "I": "*()(IJHJK",
    "J": "(OLK",
    "K": "UJMJIJ<",
    "L": "UHBN",
    "M": "VGYHNJIK<",
    "N": "UHBUJMKO",
    "O": ")(IO)",
    "P": "UJMUIKJ",
    "Q": "*&YHJI*K",
    "R": "&UJ&*IUK",
    "S": ")(*IK<MN",
    "T": "^&*&UJ",
    "U": "^YHJKI*",
    "V": "UJMKO",
    "W": "YHNJIK<LP",
    "X": "*IK(IJ",
    "Y": "*I)OKM",
    "Z": "ERTTFCCVB"
  },
  3: {
    "a": "76tgh7uj",
    "b": "3wawesa",
    "c": "43we",
    "d": "uygh8uh",
    "e": "yu76tgh",
    "f": "76tfdrty",
    "g": "iuhjijnb",
    "h": "8uhuij",
    "i": "5tg",
    "j": "6yhg",
    "k": "3ede4ef",
    "l": "6yhu",
    "m": "u8i9o",
    "n": "yhhyuj",
    "o": "98ui9",
    "p": "ijniokj",
    "q": "65ty6yh",
    "r": "t6yhhy67",
    "s": "87ujh",
    "t": "yui7ujk",
    "u": "6yu77ui",
    "v": "7uji9",
    "w": "3e4r5",
    "x": "7i8y",
    "y": "r5t6tf",
    "z": "67ygh",
    "A": "#WA#EDWE",
    "B": r"$RF$%TRRTGF",
    "C": "^%RFG",
    "D": "YGVYUJNBV",
    "E": "TGBNTYGH",
    "F": "TFCTYFG",
    "G": "&^TGHUJ",
    "H": "YGVUHBGH",
    "I": "^&*&YGFGH",
    "J": "&UJH",
    "K": "TGBGYGN",
    "L": "TFCV",
    "M": "XDRFVGYHN",
    "N": "TFCTGBHU",
    "O": "*&YU*",
    "P": "TGBTYHG",
    "Q": "^%RFGY^H",
    "R": "%TG%^YTH",
    "S": "*&^YHNBV",
    "T": r"$%^%TG",
    "U": r"$RFGHY^",
    "V": "TGBHU",
    "W": "RFVGYHNJI",
    "X": "^YH&YG",
    "Y": "^Y*UHB",
    "Z": "QWEESZZXC"
  },
  4: {
    "a": "87yhj8ik",
    "b": "4eserds",
    "c": "54er",
    "d": "iuhj9ij",
    "e": "ui87yhj",
    "f": "87ygftyu",
    "g": "oijkokmn",
    "h": "9ijiok",
    "i": "6yh",
    "j": "7ujh",
    "k": "4rfr5rg",
    "l": "7uji",
    "m": "i9o0p",
    "n": "ujjuik",
    "o": "09io0",
    "p": "okmoplk",
    "q": "76yu7uj",
    "r": "y7ujju78",
    "s": "98ikj",
    "t": "uio8ikl",
    "u": "7ui88io",
    "v": "8iko0",
    "w": "4r5t6",
    "x": "8i9u",
    "y": "t6y7yg",
    "z": "78uhj",
    "A": r"$ES$RFER",
    "B": "%TG%^YTTYHG",
    "C": "&^TGH",
    "D": "UHBUIKMNB",
    "E": "YHNMYUHJ",
    "F": "YGVYUGH",
    "G": "*&YHJIK",
    "H": "UHBIJNHJ",
    "I": "&*(*UHGHJ",
    "J": "*IKJ",
    "K": "YHNhuHM",
    "L": "YGVB",
    "M": "CFTGBHUJM",
    "N": "YGVYHNJI",
    "O": "(*UI(",
    "P": "YHNYUJH",
    "Q": "&^TGHU&J",
    "R": "^YH^&UYJ",
    "S": "(*&UJMNB",
    "T": "%^&^YH",
    "U": "%TGHJU&",
    "V": "YHNJI",
    "W": "TGBHUJMKO",
    "X": "&UJ*UH",
    "Y": "&U(IJN",
    "Z": "WERRDXXCV"
  }
};

List wrap(String pass) {
  var ans = [];
  int i;
  for (i = 0; i + 12 <= pass.length; i += 12) {
    String a = pass.substring(i, i + 12);
    ans.add(a);
  }
  ans.add(pass.substring(i, pass.length));
  return ans;
}

String add(String a, String b) {
  // print(a);
  // print(b);
  if (a == "") return b;
  String ans = "";
  if (a.length == b.length) {
    for (int i = 0; i < a.length; i++) {
      ans += sample[(a[i].codeUnitAt(0) + b[i].codeUnitAt(0)) % 72];
    }
  } else {
    for (int i = 0; i < b.length; i++) {
      ans += sample[(a[i].codeUnitAt(0) + b[i].codeUnitAt(0)) % 72];
    }
    ans += a.substring(b.length, a.length);
  }
  return ans;
}

class PRPass {
  PRPass({String this.secret, String this.lucky});
  final String secret;
  final String lucky;

  String generatePassword() {
    var luck = int.parse(this.lucky);
    // print("luck" + luck.toString());
    // print("Pass" + this.secret);
    var luck1 = luck % 5;
    String a;
    String ans = "";
    for (int i = 0; i < this.secret.length; i++) {
      a = this.secret[i];
      if (defLt.contains(a)) {
        ans += data[luck1][a];
      } else {
        ans += a;
      }
    }
    var ans1 = wrap(ans);
    luck += 100;
    luck %= 72;
    var ansFinal = sample[luck];
    for (int i = 1; i < 12; i++) {
      ansFinal += sample[ansFinal[i - 1].codeUnitAt(0) % 72];
    }
    for (int i = 0; i < ans1.length; i++) {
      ansFinal = add(ansFinal, ans1[i]);
    }
    luck += this.secret.length + ans1.length * this.secret.length;
    luck %= 72;
    String char1 = sample[(luck % 26) + 26] + sample[((luck + 111) % 10) + 52];
    String char3 = sample[((luck + 222) % 10) + 62] + sample[(luck + 300) % 26];
    luck = (this.secret.length * luck) % ansFinal.length;
    ansFinal = ansFinal.substring(0, luck) +
        char1 +
        ansFinal.substring(luck, ansFinal.length);
    luck += this.secret.length + ans1.length;
    luck %= ansFinal.length;
    ansFinal = ansFinal.substring(0, luck) +
        char3 +
        ansFinal.substring(luck, ansFinal.length);
    return ansFinal;
  }
}
